### PR TITLE
fix(design-tokens): change SG theme to inherit Default except font

### PR DESCRIPTION
**Pull request by richbachman**
- [x] Inherited everything except `font-family-10` from Default theme for SendGrid theme
- [x] Updated test in `paste-theme` package

Verified with design team that the code font family should be the same as the default theme.

### CODE REVIEW

**Review by TheSisb — APPROVED** [review]
💯

**Comment by GiantRobots** [comment]
We don't use the SGTheme in SendGrid anymore so this isn't really required.

**Comment by SiTaggart** [comment]
> We don't use the SGTheme in SendGrid anymore so this isn't really required.

This is more a risk mitigation backup plan, just in case someone is super attached to Colfax or a particular screen needs it. It's not really intended for use, and wont be advertised as such

**Comment by GiantRobots** [comment]
Sounds good just wanted y'all to know we migrated off of it!

**Pull request merged**
