### PR TITLE
chore(website): change casing of components in sidebar

### PR DESCRIPTION
**Pull request by TheSisb**
Simple tweak:

*Before*
image

*After*
image

### CODE REVIEW

**Comment by SiTaggart** [comment]
What do we think about sentence case instead? cc @aayushpi

**Comment by TheSisb** [comment]
> What do we think about sentence case instead? 

The reason I went this route is so that it reads like how you would use the component in React

`<AspectRatio>` -> `AspectRatio` in sidebar

**Comment by richbachman** [comment]
> > What do we think about sentence case instead?
> 
> The reason I went this route is so that it reads like how you would use the component in React
> 
> i.e.: `<AspectRatio>` -> `AspectRatio` in sidebar
> 
> It's the real component name.

Thats solid reasoning. I've seen that naming convention used on other design system doc sites. Specifically the Chakra Design System we all love.

**Comment by SiTaggart** [comment]
I think my only concern is that our pages aren't designed just for an engineering audience. They are for designers too and have design guidelines etc, and marking page in the nav based on the react component name seems a little... engineer first. 

Sentence case feels a little more inclusive and plain english to me

**Comment by aayushpi** [comment]
Nope. I prefer before.

**Comment by serifluous** [comment]
@aayushpi Why the earlier version?

**Comment by serifluous** [comment]
@TheSisb Separately, this casing will apply to _all_ components, right? Not just Utilities?

**Comment by two24studios** [comment]
I don't mind the casing, I prefer it over the dashes and because it maps to the component naming. In a perfect world, I think I'd rather see something like `Aspect Ratio`, `Media Object`, etc. with a space between words just to make it easier to read.

**Comment by TheSisb** [comment]
@serifluous yes all React Components (components, utilities, primitives).

I think having a consistent design language between Sketch/Abstract/Figma -> Engineering might be valuable if we end up using those tools to compose React Components and talking about the same things.

**Comment by aayushpi** [comment]
I think sentence case is easier to read

**Comment by serifluous** [comment]
+1 to sentence case.

I could see a case for title case because they're Names of Things, but sentence case would be easier to read.

**Comment by TheSisb** [comment]
Fixed to look like this now:
image


@aayushpi @two24studios @SiTaggart @serifluous

**Pull request merged**
