### PR TITLE
docs(website): add alpha combobox doc page

### PR DESCRIPTION
**Pull request by richbachman**
- [x] Combobox doc page
- [x] Expose more props for Combobox that may be useful to user
  - onHighlightedIndexChange
  - onIsOpenChange

### CODE REVIEW

**Comment by TheSisb** [comment]
The autocomplete example crashes when I try typing a letter into the combobox
image

**Comment by richbachman** [comment]
@TheSisb will you verify the crash is fixed?

**Comment by SiTaggart** [comment]
Just spotted a bug with Combobox component. The label for and input id's don't match

image

Reckon you can do a quick patch in this PR for that?

**Comment by richbachman** [comment]
@SiTaggart it looks like that might be an issue with Downshift.
image

I tried passing an `htmlFor` value directly to the label and in the `getLabelProps` function, but those get overwritten by Downshift.

**Comment by SiTaggart** [comment]
So the problem is this line in the combobox, we should be able to work around it. 

https://github.com/twilio-labs/paste/blob/master/packages/paste-core/components/combobox/src/Combobox.tsx#L96

If you need both, input props and toggle button props, then it might be the _order_ of those that matter. toggle button id is overrideing the input id.

**Comment by richbachman** [comment]
@SiTaggart just pushed up the fix for the label for attribute and a test to verify.

**Pull request merged**
