### PR TITLE
chore(website): update Patterns overview table

### PR DESCRIPTION
**Pull request by loreina**
- Updated query to include patterns that are in development and in production
- Removed patterns from "most requested" tab that are in development
- Alphabetize most requested patterns
- Removed `<contentwrapper>` and `<content>` so the Patterns overview page content is the full width like the Components page

### CODE REVIEW

**Review by SiTaggart — APPROVED** [review]
Looks good from a code perspective

**Comment by katieporter** [comment]
Thank you for doing this, it looks awesome!

While you're in here, is it possible to center this table header?
image

Aaaand, this is totally optional, but if you're feeling super ambitious, you could update our Overview pages to use the status pattern as per [these designs](https://www.figma.com/file/w8Usm0zhowDJJ9kig5qm3Y/Component-Page-Updates---2021?node-id=48%3A9054). ;) 100% optional though, for real.

**Comment by loreina** [comment]
@katieporter I centered the Peer review table header and re-requested review. Gonna leave the table design update for the engineering pros

**Review by TheSisb — APPROVED** [review]

**Review by shleewhite — APPROVED** [review]
🚢

**Pull request merged**
