### PR TITLE
chore: minor vs code plugin package improvements

### PR DESCRIPTION
**Pull request by TheSisb**
- [x] Update the readme
- [x] Update the package.json
- [x] Add LICENSE file
- [x] Verify publishing works 👍

### CODE REVIEW

**Review by gkassym — APPROVED** [review]
LGTM

**Review by SiTaggart — COMMENTED** [review]
Question: The version number we have in the package json here, are we intending to version the plugin via changesets? Or is that handled else where in the VS Code / Azure workflows?

**Comment by TheSisb** [comment]
the version is handled elsewhere by the `vsce` npm binary as documented

**Review by SiTaggart — DISMISSED** [review]
Maybe try private package in the package.json and we're good to go otherwise

**Pull request merged**
