### PR TITLE
docs(website): content update for home page

### PR DESCRIPTION
**Pull request by aayushpi**
Homepage content update to call out components, content, and layout more explicitly. Here's a screenshot of the intended effect:

image

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [X] I acknowledge that all my contributions will be made under the project's license.

> Can't really explain what about the anchors on the headings is throwing me off, but could you try putting anchors underneath each text block?
> 
> Might be throwing me off because all the clickable things are bunched together in the middle of the screen, or that the flow of the top section has static text above interactive things, but the bottom sections have interactive things above static text.

tried something different in the newest update

### CODE REVIEW

**Comment by SiTaggart** [comment]
@aayushpi any chance we can add a third button after roadmap so we can keep a link to the sandbox on the homepage?

**Comment by serifluous** [comment]
Can't really explain what about the anchors on the headings is throwing me off (maybe it's because all the clickable things are bunched together in the middle of the screen), but could you try putting anchors underneath each text block?

**Comment by aayushpi** [comment]
> I like this, but I do have a concern that there is no longer a clear primary call to action. Maybe that's fine and we want this to be a "choose your own adventure" situation, but I could see folks getting a little bit overwhelmed about what to do next. I personally liked the "getting started" action as a clear primary CTA.

Would a "Get Started" heading above the unordered list help?

**Comment by serifluous** [comment]
> > I like this, but I do have a concern that there is no longer a clear primary call to action. Maybe that's fine and we want this to be a "choose your own adventure" situation, but I could see folks getting a little bit overwhelmed about what to do next. I personally liked the "getting started" action as a clear primary CTA.
> 
> Would a "Get Started" heading above the unordered list help?

Or a "Getting started" link that's the same text size as the text block above the list, though that might make the two other bullet points look a little lonely.

The separator helps the content flow more now from top to bottom imo  👍

**Comment by katieporter** [comment]
> > > I like this, but I do have a concern that there is no longer a clear primary call to action. Maybe that's fine and we want this to be a "choose your own adventure" situation, but I could see folks getting a little bit overwhelmed about what to do next. I personally liked the "getting started" action as a clear primary CTA.
> > 
> > 
> > Would a "Get Started" heading above the unordered list help?
> 
> Or a "Getting started" link that's the same text size as the text block above the list, though that might make the two other bullet points look a little lonely.
> 
> The separator helps the content flow more now from top to bottom imo 👍

Yeah I think a "Getting started" header could help. I also wonder if we could take the links out of the unordered list or just stack them? Doesn't feel totally necessary to have the bullet points but I don't feel super strongly about it. I think it looks good!

**Pull request merged**
