### PR TITLE
chore: product designer auto review assignment

### PR DESCRIPTION
**Pull request by SiTaggart**
Based on changes being reported in Chromatic, auto assign a product designer to the PR for approval.

# EDIT

This works, but I cannot for the life of me get `delivery-much/actions-assigner` to assign the design team alias as the reviewer so it round robins the assignee. Chromatic now reports back correctly and we can act on it, but the action won't assign the team reviewer

### CODE REVIEW

**Review by TheSisb — APPROVED** [review]
neat, but dont forget to undo the test in badge

**Comment by TheSisb** [comment]
It's set to ignore drafts and didn't assign anyone, so I made it a full PR to see if it works

**Comment by SiTaggart** [comment]
It doesn't yet, they need to accept my PR to Chromatic CLI. Linked above ^

**Review by TheSisb — APPROVED** [review]

**Comment by SiTaggart** [comment]
Doesn't work and we've got way less designers now.

**Pull request closed without merging**
