### PR TITLE
feat(icons): adding toolbar related icons

### PR DESCRIPTION
**Pull request by gloriliale**
Added the following 9 icons:

- AttachmentIcon
- BoldIcon
- FileIcon
- HistoryIcon
- ItalicIcon
- OrderedListIcon
- StrikethroughIcon
- UnderlineIcon
- UnorderedListIcon

### CODE REVIEW

**Review by SiTaggart — APPROVED** [review]
I think it looks good

**Review by TheSisb — COMMENTED** [review]
Missing a changeset, the rest lgtm

**Review by TheSisb — APPROVED** [review]

**Review by loreina — APPROVED** [review]
I used the deploy preview to check the icons against the designs on Figma and lgtm 👍 👍 👍 

Not sure you want @katieporter to also review this since she designed most of these

**Comment by loreina** [comment]
Friendly reminder to follow up with the people who requested some icons. I think they're listed in the AC :)

**Pull request merged**
