### PR TITLE
feat: 404 page and empty states

### PR DESCRIPTION
**Pull request by TheSisb**
This PR adds a 404 page that renders content based on the URL you landed on.
If you landed on a component that is planned and not completed, it will say "not built"
If you landed on an unplanned page, it will say "not found"

--- 

### NotBuilt
image
image

### NotFound
image

---

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

### CODE REVIEW

**Comment by SiTaggart** [comment]
Potential feature creep: For the packages that are beta or alpha that don’t have a current page, would it be an idea to have a 3rd state of “In development - we just haven’t written the docs yet”?

It might better reflect the state of things in the system.

So on the overview pages all components could be links which would hit the “on the roadmap” page, the components in dev that appear at the top of the list get their own page saying as such, and complete components get to navigate?

Just a thought

**Comment by aayushpi** [comment]
+1 to @SiTaggart --> Higher comms is better

**Comment by TheSisb** [comment]
> So on the overview pages all components could be links which would hit the “on the roadmap” page, the components in dev that appear at the top of the list get their own page saying as such, and complete components get to navigate?

I'm not sure I'm into the idea of making a bunch of links that lead to an empty state, at least in the projects current state where 90%+ is empty.  I like the idea of `in development` for packages that don't have docs but aren't v0.0.0.   I will make that out of scope change for now.

**Comment by TheSisb** [comment]
@aayushpi @SiTaggart 
image

Something like this?

**Comment by SiTaggart** [comment]
🚢

**Pull request merged**
