### PR TITLE
chore(website): add link to our copy-to-clipboard library to website

### PR DESCRIPTION
**Pull request by andipants12**
## Description

Due to our temporary HAP we are not able to pick up the work of adding a copy to clipboard pattern to our docs website. This(these) commit(s) add a link to the library source code, along with some brief context on how we use it.

> Screen Shot 2022-05-25 at 3 14 21 PM

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

### CODE REVIEW

**Review by TheSisb — APPROVED** [review]
LGTM.

Mind if I scope creep and ask ya to add links to the Codemods and Data Visualization pages on this overview page too? They show up in the sidebar but we forgot to add them in the overview.

**Comment by katieporter** [comment]
question: this library was a contribution (I think)—do we want to call that out and give props to the contributor?

**Comment by katieporter** [comment]
nitpit: not sure if this is possible, but it'd be nice if the external link icon were inside the code snippet.

**Comment by andipants12** [comment]
> nitpick: not sure if this is possible, but it'd be nice if the external link icon were inside the code snippet.

@katieporter I'll take a look and will add it in if it's a simple lift. Thanks!

**Review by gloriliale — APPROVED** [review]
Into it!

**Pull request merged**
