### PR TITLE
feat(icons): add EIP product icon

### PR DESCRIPTION
**Pull request by PabloFNK**
Adding Product Icon for EIP so we can use it on Console.Zen navigation. There is a discussion about this here: https://github.com/twilio-labs/paste/discussions/971

### CODE REVIEW

**Review by TheSisb — APPROVED** [review]
cc @serifluous - lgtm

**Comment by PabloFNK** [comment]
Sorry for the ping @TheSisb and @serifluous . I would like, if possible, merge this before Tweek as I would like also to open a PR to Console.Zen using this icon. Thanks!

**Comment by serifluous** [comment]
Thanks, @PabloFNK ! I'm not too fussed about visuals since it'll be replaced by the Brand-provided one soon (based on the discussion from #971. I chatted a bit with Elaine about this now, too, and she's good with it).

Can you rename the icon to ProductEngagementIntelligencePlatformIcon? It's a little wordy, unfortunately, but it'll help folks avoid ambiguity and make it easier to search in our icon list.

**Comment by PabloFNK** [comment]
@serifluous Icon name updated!

**Review by serifluous — APPROVED** [review]

**Comment by PabloFNK** [comment]
Some concerns arround this right now. 

- I have checked what Vercel has deployed and it has been with the old icon name 😢 
- The branch is out of sync with `main`. I was going to update it but `main` branch is failing on `yarn type-check`.

Screenshot 2020-12-03 at 10 43 24

**Comment by SiTaggart** [comment]
All good, I pushed this commit to our repo so the full checks can run and everything looked good to me. It's merged and will be released soon. https://github.com/twilio-labs/paste/pull/994

For extra context the type check will fail if you don't rerun the build, as it's type-checking against often stale or old assets locally.

**Pull request closed without merging**
