### PR TITLE
fix(design-tokens): change color-text-link token values

### PR DESCRIPTION
**Pull request by richbachman**
- [x] Updated Console color-text-link values
- [x] Updated SendGrid color-text-link values
- [x] Added color-text-icon-* values for Console and SendGrid
- [x] Updated tests

### CODE REVIEW

**Comment by serifluous** [comment]
lgtm!

**Comment by TheSisb** [comment]
Can I get some context on why we added `color-text-icon-*` tokens please?  Icons should only accept text colors, and I'm not noticing any deviation in color either

**Comment by richbachman** [comment]
@serifluous will you add some context on the `color-text-icon-*` additions?

**Comment by serifluous** [comment]
> Can I get some context on why we added `color-text-icon-*` tokens please? Icons should only accept text colors, and I'm not noticing any deviation in color either

Cool ok, didn't realize that. There are no color differences with these link ones. We can remove the icon ones.

**Comment by richbachman** [comment]
@TheSisb @serifluous `color-text-icon-*` have been removed.

**Pull request merged**
