### PR TITLE
chore: delay some flakey chromatic snapshots

### PR DESCRIPTION
**Pull request by SiTaggart**
Try and get Chromatic to pass all the time when you don't actually change anything in a component.

### CODE REVIEW

**Comment by TheSisb** [comment]
Doesn't look like it worked. :(

I like this PR.

**Comment by SiTaggart** [comment]
Opened a support ticket with Chromatic so we can use this to work through it

**Comment by SiTaggart** [comment]
@TheSisb So I ran these 3 times in a row and everything seems to be passing each time. 

We obviously would see some diffs between main, as the timing of the snapshots is also different on main as the branch. But once the initial diff was accepted on this branch, if they were flakey I would expect to see if fail on re-runs, which it's not.

🤞 Fingers crossed

**Review by TheSisb — APPROVED** [review]
:|

**Review by richbachman — APPROVED** [review]

**Pull request merged**
