### PR TITLE
fix: remove the underline from button states

### PR DESCRIPTION
**Pull request by SiTaggart**
Because we have now fixed the contrast of the button hover and focus states with the outline color, we can now remove the text underline. 

Fixes https://github.com/twilio-labs/paste/issues/54

### CODE REVIEW

**Comment by richbachman** [comment]
It looks like that change killed the hover underline on the reset variant: https://paste-git-feat-remove-button-underline.twilio-dsys.now.sh/components/button#examples

Original here for comparison: https://paste.twilio.design/components/button#examples

**Comment by SiTaggart** [comment]
> It looks like that change killed the hover underline on the reset variant: 

So, this was by accident, but it does raise the question of; should a `reset` button have any styles like underlines on hover?

**Comment by serifluous** [comment]
I keep asking @TheSisb again and again about what `reset` is for, and I keep forgetting. Can someone remind me? 😬

As a stab in the dark, I'm going to say it should still keep the underline on hover.

**Comment by TheSisb** [comment]
The Button component has a`reset` for `size` and a `reset` for `variant`.

The `variant reset` simply removes all the default button styles.  We added this in the first pass of the component but I'm no longer convinced we should have it.  I think it's safe to remove it knowing what we now know.

The `size reset` omits adding the Button font-size, line-height, border-radius, font-weight, and padding that other sizes set.  This was useful for buttons as links, where the additional padding seemed off.

Reflecting on those decisions, I think we should change our variants into a tuple shaped as `level_look`.  This allows us to add new variants with relative ease.

Example:
```
- primary_filled
- primary_outlined
- primary_link
- destructive_filled
- destructive_outlines
- destructive_link
```

**Comment by TheSisb** [comment]
I approved the PR because this change is fine.  We should follow it up with some additional Button work.

**Comment by richbachman** [comment]
@TheSisb thanks for the explanation and background.

**Pull request merged**
